# Generated by Django 5.0.4 on 2024-04-09 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Member",
            new_name="Agents",
        ),
    ]
