# Generated by Django 5.0.4 on 2024-04-09 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_rename_member_agents"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Agents",
            new_name="Members",
        ),
    ]
