# Generated by Django 5.0.4 on 2024-04-09 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_rename_agents_members"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Users",
        ),
    ]
