# Generated by Django 5.0.4 on 2024-04-09 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_rename_members_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="Member",
        ),
    ]
