# Generated by Django 5.0.4 on 2024-04-10 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_rename_users_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="firstName",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="lastName",
            new_name="username",
        ),
    ]
